name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Deno
      run: curl -fsSL https://deno.land/x/install/install.sh | sh
    - uses: actions/checkout@v1
    - name: Run tests
      run: /home/runner/.local/bin/deno --allow-read --allow-write test.ts
    - name: Run benchmarks
      run: /home/runner/.local/bin/deno bench.ts
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Install Deno
      run: curl -fsSL https://deno.land/x/install/install.sh | sh
    - uses: actions/checkout@v1
    - name: Build docs
      # Update this, if more files are to be included in build ...
      run: /home/runner/.local/bin/deno --allow-read --allow-write docs/generate.js docs/api.md mod.ts src/db.js src/rows.js
    - uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Automatically update documentation
        branch: master
        file_pattern: docs/**.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
